# Generated by Django 2.2.7 on 2019-11-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_text',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_polls.Course')),
            ],
        ),
    ]
