# Generated by Django 2.2.7 on 2020-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='describe',
            field=models.CharField(default='', max_length=700),
        ),
    ]
