# Generated by Django 2.2.7 on 2019-11-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0003_language_profile_traineee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineee',
            name='language',
        ),
        migrations.AddField(
            model_name='traineee',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training_polls.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traineee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_polls.Profile'),
        ),
    ]
