# Generated by Django 2.2.7 on 2019-11-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0004_auto_20191109_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineee',
            name='language',
        ),
        migrations.RemoveField(
            model_name='traineee',
            name='profile',
        ),
    ]
