# Generated by Django 2.2.7 on 2019-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0005_auto_20191109_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Traineee',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
