# Generated by Django 2.2.7 on 2019-11-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0006_auto_20191109_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainee',
            new_name='ListTrainee',
        ),
    ]
