# Generated by Django 2.2.7 on 2019-11-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0007_auto_20191109_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='listtrainee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_polls.Language'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
