# Generated by Django 2.2.7 on 2019-11-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0008_auto_20191109_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtrainee',
            old_name='course',
            new_name='language',
        ),
    ]
