# Generated by Django 2.2.7 on 2019-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0009_auto_20191109_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtrainee',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
