# Generated by Django 2.2.7 on 2019-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0010_auto_20191110_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtrainee',
            name='id',
        ),
        migrations.AddField(
            model_name='listtrainee',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
