# Generated by Django 2.2.7 on 2019-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0011_auto_20191127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtrainee',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
