# Generated by Django 2.2.7 on 2019-11-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_polls', '0012_auto_20191127_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtrainee',
            old_name='auto_increment_id',
            new_name='id_field',
        ),
    ]
